###########################################################
#                          HvsV                           #
#                          v1.0                           #
###########################################################
settings:
  world: "game"
  coords: # Координаты спавна
    x1: -1000
    z1: -1000
    y: 100
    x2: 1000
    z2: 1000
  radius: 50 # Радиус проверки на сторонние локации рядом.
  # N - Спавн локация
  category:
    H: "schematics/%map%/hause"
    T: "schematics/%map%/weapon"
    X: "schematics/%map%/spawn"
    N: "schematics/%map%/no"
  spawns: "N" # По примеру генерации карты через пробел можно добавлять спавны для категорий schematic.
  items: "T" # Где будет спавниться топорик, так же как и через spawns.
  hunters: "X" # Места, где будут спавняться охотники.
  # Настройте генерацию карты:
  map:
    - "H N X"
    - "N T N"
    - "H N H"
  game:
    players: # Онлайн при котором допустимо начать игру.
      min: 3
      medium: 5
      max: 8
    waitTime: # Время ожидания по онлайну выше.
      min: 60
      medium: 30
      max: 1
    endTime: 241 # Через сколько секунд после начала закончится игра.
    playersHun: # Здесь перечислено кол-во игроков и количество охотников. ИГРОКИ:ОХОТНИКИ (Игроки - онлайн на карте). # Начинайте с большего по нижний онлайн.
      - "8:3"
      - "5:2"
      - "3:1"
    role:
      victim:
        health: 6 # 20 - все 10 сердечек. 6 - 3 сердечка.
        damage: 2 # Урон, который может нанести жертва по охотнику. 2 - 1 сердечко.
      hunter:
        health: 10 # 20 - Все 10 сердечек. 10 - 5 сердечек.
        damage: 2 # Урон, который может нанести охотник по жертве. 2 - 1 сердечко.
        spawn: 60 # Через сколько секунд их телепортируют из клеток?
    items:
      exit:
        material: "BARRIER"
        name: "&cВыйти"
        lore: []
      victim:
        weapon: "IRON_AXE"
        spawn: 120 # Через сколько заспавнится топор (В секундах).
        respawn: 5 # Через сколько секунд в случае смерти жертвы перезаспавнится топор.
      hunter:
        weapon: "DIAMOND_SWORD"
        helmet: "MOB_SPAWNER"
    armorstand:
      loc:
        x: -1
        y: 2
        z: 0
      rightFace:
        x: -100
        y: 0
        z: 0

#
# Чтобы поставить новые строчки в сообщениях воспользуйтесь: \n
#
messages: # Сообщения
  # [message] сообщение - Отправить сообщение игроку.
  # [broadcast] сообщение - Отправить сообщение всему серверу.
  # [title] сообщение1;сообщение2 - Отправить титул игроку.
  # [player] команда - Выполнить команду от имени игрока.
  # [console] команда - Выполнить команду от имени консоли.
  # [sound] sound;volume;pitch - Выполнить звук для игрока.
  # Добавьте перед действиями [hunters] или [victims],
  # чтобы отправить сообщение одной роли.
  # Пример: [hunters] [message] Привет охотники!
  cmd: # Сообщения от команды hvsv
    help:
      - "&a[HVSV] Помощь &7(/hvsv help):"
      - ""
      - "&a/hvsv status &f- Посмотреть статус плагина."
      - "&a/hvsv join &f- Создать или подключиться к любой свободной комнате."
      - "&a/hvsv join roomid &f- Попытка подключения к комнате (если она свободна)."
      - "&a/hvsv reload &f- Перезагрузить конфигурацию плагина."
      - ""
    noperm:
      - "&cУ вас недостаточно прав!"
  game:
    room:
      notfound: "&cДанная комната не создана."
      started: "&cИгра уже началась."
      connect: "&aПодключаем к комнате &e%room%..."
    role:
      victim: "&aЖертва"
      hunter: "&cОхотник"
    status:
      stopped: "&fДля старта нужно: &e%min_players%"
      wait: "&fЗапуск через: &e%time% &fсек."
      start: "&fДо конца игры: &e%time%"
      win_victim: "&aЖертвы победили!"
      win_hunter: "&cОхотники победили!"
    actions:
      no:
        - "[message] &cВы находитесь в игре!"
      end:
        - "[message] &cИгра окончена."
      kicked:
        - "[message] &cИгра окончена."
      join:
        - "[message] &fИгрок &e%player% &aприсоединился к игре. &f(&e%amount%&f/&e%max_players%&f)"
      quit:
        - "[message] &fИгрок &e%player% &cвышел из игры. &f(&e%amount%&f/&e%max_players%&f)"
      role:
        - "[message] &fВы %role%!"
        - "[title] &fРоль:;%role%"
        - "[message] &cОхотники &fскоро выберутся. Успейте спрятаться!"
      killHunter:
        - "[message] &fЖертва &a%victim% &cобезвредела&f охотника &c%hunter%"
      killVictim:
        - "[message] &fОхотник &c%hunter%, &cубил&f жертву &a%victim%"
      exitHun:
        - "[victims] [message] &cОхотники &fвышли из заточения!"
        - "[victims] [title] &cОхотники;&fвышли!"
      startAxe:
        - "[message] &aТопор&f появился!"
        - "[title] &aТопор;&fпоявился!"
      getAxe:
        - "[message] &fИгрок &e%player% &fподобрал топорик! &cБегите охотники!"
      win_hunter:
        - "[message] &cПобедили охотники!"
        - "[title] &cОхотники;&fпобедили!"
      win_victim:
        - "[message] &aПобедили жертвы!!"
        - "[title] &aЖертвы;&fпобедили!"